[package]
name = "scout"
version = "0.1.0"
authors = ["Sam Stelfox <sstelfox@bedroomprogrammers.net>"]

[dependencies]
actix = "^0.5"
actix-web = { version = "^0.6", default-features = false }
dotenv = "^0.12"
env_logger = "^0.5"
log = "^0.4"
