[package]
name = "scout"
version = "0.1.0"
authors = ["Sam Stelfox <sstelfox@bedroomprogrammers.net>"]

[dependencies]
actix = "0.5.8"
actix-web = { version = "0.6.9", default-features = false }

dotenv = "0.12.0"
env_logger = "0.5.10"
log = "0.4.1"

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

diesel = { version = "^1.3", features = ["postgres"] }
